[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
droplinked_autonomous_program = "Du3qfvSDkDq92p9dYV6XhRPW6TRRtHbGnH3tiNfJjYWp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
